name: Github Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: Install dependencies and build
        run: |
          yarn install
          yarn build
      - name: Deploy
        env:
          CI: false
        run: |
          yarn run gh-pages -d ./build -t ${{ secrets.GITHUB_TOKEN }}
