name: React app deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Switch to main branch
      run: |
        git checkout main
        git pull origin main


    - name: Deploy react app to github pages
      run: |
        echo "Deploying react app to github pages"
        npm i
        npm run build
        npm ci
        npx react-scripts build
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -m "Automatic Deploy action run by github-actions"
        git push origin HEAD:gh-pages --force
